name: actions
run-name: WhiteSunOfSpace is running lab04
on: [push]
jobs:
  container-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test project
        run: chmod -x "test.sh"
        run: ./.github/workflows/test.sh
